export const PRIVACY_POLICY_LAST_UPDATED = 'April 21, 2026'

export const PRIVACY_POLICY_META_DESCRIPTION =
  'Read how Medha Clinic handles website, blog, comment, and contact information, including data use, sharing, retention, security, and deletion requests.'

export const PRIVACY_POLICY_CONTACT = {
  clinicName: 'Medha Clinic',
  email: 'info@medhaclinic.com',
  phone: '+91 98008 08595',
  address: '12 B.T. Road, Near Dunlop L-9 Bus Stop, Baranagar, Kol-56',
  canonicalUrl: 'https://medhaclinic.com/privacy-policy',
}

export const PRIVACY_POLICY_HIGHLIGHTS = [
  'Applies to medhaclinic.com, public blog features, and direct communications that reference this page.',
  'Covers current website behavior reviewed in this codebase, including blog search, likes, shares, comments, and public contact channels.',
  'The current public site code reviewed does not show consumer account login, payment checkout, or continuous precise location tracking.',
  'Privacy, correction, and deletion requests can be sent to info@medhaclinic.com.',
]

export const PRIVACY_POLICY_SECTIONS = [
  {
    id: 'scope',
    title: 'Who This Policy Applies To',
    paragraphs: [
      'This Privacy Policy explains how Medha Clinic collects, uses, stores, and shares information when you use https://medhaclinic.com, read our public blog, submit a blog comment, contact us, or interact with website features that reference this page.',
      'This page is based on the current public website codebase reviewed on April 21, 2026. If Medha Clinic introduces new app, account, reminder, upload, payment, wellness tracking, or patient portal features, this policy should be updated before or when those features are launched.',
    ],
  },
  {
    id: 'information-we-collect',
    title: 'Information We Collect',
    blocks: [
      {
        heading: 'Information you provide directly',
        bullets: [
          'Contact and consultation details such as your name, email address, phone number, gender, preferred date or time, doctor or department choice, and message content when you submit that information through a public form or direct communication channel.',
          'Blog comment details, including your name, phone number, and the comment you choose to submit. From the current frontend code, your name and comment may be displayed publicly if the comment is published.',
          'Information you choose to share when contacting Medha Clinic by email, phone, WhatsApp, or social media.',
        ],
      },
      {
        heading: 'Information collected automatically or from your browser',
        bullets: [
          'Standard technical information such as IP address, browser type, device information, pages visited, referrer URL, approximate location inferred from IP, timestamps, and security or error logs generated by hosting, API, or infrastructure providers.',
          'Search terms entered into the website blog search.',
          'A local browser storage entry used to remember whether you liked a blog post on a particular device.',
        ],
      },
      {
        heading: 'What the current public site code does not appear to collect directly',
        bullets: [
          'Consumer account registration or login credentials.',
          'Payment card checkout data.',
          'Continuous precise geolocation.',
          'A public upload tool for patient images, documents, or reports through this website interface.',
        ],
      },
    ],
  },
  {
    id: 'how-we-use-information',
    title: 'How We Use Information',
    bullets: [
      'To operate the website, blog, navigation, and public features.',
      'To respond to inquiries, consultation requests, and support messages.',
      'To publish, moderate, or remove blog comments and reduce spam or misuse.',
      'To deliver blog content, embedded media, and sharing functionality.',
      'To understand how public content is being used, troubleshoot technical issues, and improve site performance.',
      'To protect the website, our users, and Medha Clinic from abuse, fraud, unauthorized access, or legal risk.',
      'To comply with applicable law, lawful requests, accounting obligations, and internal record-keeping needs.',
    ],
  },
  {
    id: 'sharing-and-disclosure',
    title: 'How We Share Information',
    paragraphs: [
      'Medha Clinic does not sell personal information from this public website. We may share information only when it is reasonably necessary to run the site, respond to you, or comply with law.',
    ],
    blocks: [
      {
        heading: 'We may share information with',
        bullets: [
          'Hosting, infrastructure, and technical service providers that help operate the website and supporting API services, including providers used to host the public site and blog content.',
          'Communications or productivity providers when you contact us through email, phone, WhatsApp, or social channels.',
          'Google services where relevant to current website behavior, such as Google Fonts, and Google or YouTube if embedded video content is loaded.',
          'Social or messaging platforms such as Facebook, X, LinkedIn, WhatsApp, or your email provider when you intentionally use share or contact links from the site.',
          'Professional advisers, regulators, law enforcement, or other parties when disclosure is legally required or reasonably necessary to protect rights, safety, or the integrity of the service.',
        ],
      },
      {
        heading: 'Public content notice',
        paragraphs: [
          'If you submit a blog comment, the comment and your name may appear publicly on the site. Please avoid posting sensitive personal or health information in public comment fields.',
        ],
      },
    ],
  },
  {
    id: 'cookies-storage-and-third-party-content',
    title: 'Cookies, Browser Storage, and Third-Party Content',
    paragraphs: [
      'The current public site code reviewed does not show a broad advertising or analytics cookie stack. It does use standard browser and network functionality, including local browser storage, server logs, and third-party resources needed to render parts of the experience.',
    ],
    bullets: [
      'Local storage is used to remember whether you already liked a blog post on a device.',
      'Google Fonts may receive limited browser request information when the site loads fonts.',
      'If a blog post includes an embedded YouTube video, Google or YouTube may receive device, browser, and interaction data when that content loads or plays.',
      'If you use a share button, the destination platform may receive your IP address, browser data, and the page URL you chose to share.',
      'Your browser may also store its own cache, cookies, or connection records according to browser settings and third-party provider behavior.',
    ],
  },
  {
    id: 'retention-and-deletion',
    title: 'Data Retention and Deletion Requests',
    paragraphs: [
      'We keep personal information only for as long as reasonably necessary for the purpose it was collected, including responding to requests, operating the site, maintaining records, protecting against misuse, and meeting legal, tax, accounting, or backup obligations.',
    ],
    blocks: [
      {
        heading: 'Examples',
        bullets: [
          'Contact or consultation-related information may be kept for follow-up, service coordination, safety, and record-keeping.',
          'Blog comments may remain published until removed, moderated, or no longer needed.',
          'Technical logs are usually retained for security, troubleshooting, and operational purposes for a limited period.',
          'A liked-blog preference stored in your browser remains on your device until you clear browser storage or use a different browser or device.',
        ],
      },
      {
        heading: 'Deletion requests',
        paragraphs: [
          'The current public website code reviewed does not include a self-service consumer account dashboard. If you want Medha Clinic to review, correct, or delete contact or comment information associated with you, email info@medhaclinic.com or call +91 98008 08595. We may need to verify your identity before acting on a request, and we may retain limited information where law, safety, fraud prevention, backup integrity, or legitimate record-keeping requires it.',
        ],
      },
    ],
  },
  {
    id: 'security',
    title: 'Security',
    paragraphs: [
      'We use reasonable administrative, technical, and organizational safeguards appropriate to a public website and its supporting services, such as access controls, platform security features, and efforts to limit unauthorized access.',
      'No website, transmission method, or storage system is completely secure. You should avoid sending highly sensitive health or personal information through public comment fields or unsecured channels.',
    ],
  },
  {
    id: 'your-choices',
    title: 'Your Choices and Rights',
    bullets: [
      'You can choose not to submit optional information through forms, comments, email, phone, or social channels.',
      'You can request access, correction, or deletion of information you previously provided to us, subject to verification and applicable law.',
      'You can avoid using share buttons, embedded media, or social links if you do not want those third-party providers to process your interaction.',
      'You can clear browser cache, cookies, and local storage through your device or browser settings.',
      'If you no longer want email follow-up from Medha Clinic, you can ask us to stop using your email for that purpose.',
    ],
  },
  {
    id: 'children',
    title: 'Children and Family Information',
    paragraphs: [
      'This public website is not designed for children to use independently. If a parent, guardian, or caregiver shares information about a child with Medha Clinic, they should do so only when they are authorized to make that submission.',
      'If you believe a child has provided personal information to us without appropriate consent, please contact us so we can review and address the situation.',
    ],
  },
  {
    id: 'international-transfers',
    title: 'International Data Transfers',
    paragraphs: [
      'Because the website uses internet infrastructure and third-party technology providers that may operate in more than one country, your information may be processed or stored outside the country where you access the site.',
      'When that happens, we expect our providers to handle data using reasonable safeguards appropriate to the service they provide.',
    ],
  },
  {
    id: 'wellness-and-medical-scope',
    title: 'Wellness and Medical Scope',
    paragraphs: [
      'Medha Clinic presents public content and service information for general educational, wellness support, and informational purposes. This website is not a substitute for emergency care, hospital treatment, medical diagnosis, or urgent clinical decision-making.',
      'If you are facing a medical emergency, please seek immediate hospital or emergency care instead of relying on website content or delayed online communication.',
    ],
  },
  {
    id: 'changes',
    title: 'Changes to This Policy',
    paragraphs: [
      'We may update this Privacy Policy from time to time to reflect changes in our website, services, legal obligations, or data practices. When we make material updates, we will post the revised version on this page and update the Last updated date.',
    ],
  },
  {
    id: 'contact',
    title: 'Contact Medha Clinic',
    paragraphs: [
      'For privacy questions, correction requests, deletion requests, or concerns about how your information is handled, contact Medha Clinic using the details below.',
    ],
    bullets: [
      'Email: info@medhaclinic.com',
      'Phone: +91 98008 08595',
      'Address: 12 B.T. Road, Near Dunlop L-9 Bus Stop, Baranagar, Kol-56',
    ],
  },
]
